"""empty message

Revision ID: 7181981b072e
Revises: cf5a5241d8f1
Create Date: 2019-08-30 17:33:12.761330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7181981b072e'
down_revision = 'cf5a5241d8f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish_categories', sa.Column('level', sa.Integer(), nullable=False))
    op.add_column('dish_categories', sa.Column('lft', sa.Integer(), nullable=False))
    op.add_column('dish_categories', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('dish_categories', sa.Column('rgt', sa.Integer(), nullable=False))
    op.add_column('dish_categories', sa.Column('tree_id', sa.Integer(), nullable=True))
    op.create_index('dish_categories_level_idx', 'dish_categories', ['level'], unique=False)
    op.create_index('dish_categories_lft_idx', 'dish_categories', ['lft'], unique=False)
    op.create_index('dish_categories_rgt_idx', 'dish_categories', ['rgt'], unique=False)
    op.create_foreign_key(None, 'dish_categories', 'dish_categories', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dish_categories', type_='foreignkey')
    op.drop_index('dish_categories_rgt_idx', table_name='dish_categories')
    op.drop_index('dish_categories_lft_idx', table_name='dish_categories')
    op.drop_index('dish_categories_level_idx', table_name='dish_categories')
    op.drop_column('dish_categories', 'tree_id')
    op.drop_column('dish_categories', 'rgt')
    op.drop_column('dish_categories', 'parent_id')
    op.drop_column('dish_categories', 'lft')
    op.drop_column('dish_categories', 'level')
    # ### end Alembic commands ###
